# Generated by Django 6.0.1 on 2026-01-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_invoice_client_alter_invoice_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='date_by',
            new_name='created_at',
        ),
    ]
